# Setup
title:               kevanchristmas.io
tagline:             'Minimum Viable Product'
description:         'What it says in the about'
url:                 https://kevanchristmas.GitHub.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kevan Christmas
  url:               https://kevanchristmas.github.io/
  email:             kevan@the10x.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-540QE5TSQ5 
